---
- name: Copy vocabulary data
  synchronize: src=/Users/ryan/tmp/omop/vocabulary_4_csv dest=~/omop_vocab

- name: Copy loadmop
  synchronize: src=/Users/ryan/projects/outins/loadmop dest=~

- name: Copy loadmop modified Gemfile
  copy: src=Gemfile dest=/home/vagrant/loadmop/Gemfile

- name: Copy database.yml
  copy: src=database.yml dest=/home/vagrant/loadmop/config/database.yml

- name: fix permissions on loadmop
  file: path=/home/vagrant/loadmop recurse=yes owner=vagrant group=vagrant
  sudo: yes

- name: Setup Gemfile through sequelizer
  command: bash -lc 'cd ~/loadmop && bundle exec ruby ../sequelizer/bin/sequelizer update_gemfile'

- name: Install bundler
  command: bash -lc 'bundle --version || gem install bundler'
  register: _cql_install_bundler
  changed_when: _cql_install_bundler.stdout.find('fully installed') != -1

- name: Install gems via bundler
  command: bash -lc 'cd ~/loadmop && bundle'
  register: _cql_install_gems_via_bundler
  changed_when: _cql_install_gems_via_bundler.stdout.find('Installing') != -1

- name: Setup vocabulary database
  command: bash -lc 'cd ~/loadmop && bundle exec ruby bin/loadmop create_vocab_database ~/omop_vocab'
