---
- name: Copy loadmop
  synchronize: src=/Users/ryan/projects/outins/loadmop dest={{ tcql.dest_dir }}

- name: Create config directory
  file: dest={{ loadmop_dir }}/config state=directory

- name: Copy database.yml
  copy: src=database.yml dest={{ loadmop_dir }}/config/database.yml

- name: fix permissions on loadmop
  file: path={{ loadmop_dir }} recurse=yes owner={{ tcql.user }} group={{ tcql.group }}
  sudo: yes

- name: Install bundler
  command: bash -lc 'bundle --version || gem install bundler'
  register: _cql_install_bundler
  changed_when: _cql_install_bundler.stdout.find('fully installed') != -1

- name: Install gems via bundler
  command: bash -lc 'cd {{ loadmop_dir }} && bundle'
  register: _cql_install_gems_via_bundler
  changed_when: _cql_install_gems_via_bundler.stdout.find('Installing') != -1

- name: Setup Gemfile through sequelizer
  command: bash -lc 'cd {{ loadmop_dir }} && bundle exec sequelizer update_gemfile'

- name: Install gems via bundler
  command: bash -lc 'cd {{ loadmop_dir }} && bundle'
  register: _cql_install_gems_via_bundler
  changed_when: _cql_install_gems_via_bundler.stdout.find('Installing') != -1

- name: Setup vocabulary database
  command: bash -lc 'cd {{ loadmop_dir }} && bundle exec ruby bin/loadmop create_vocab_database {{ omop_vocab_dir }}'
