---
- name: Install some TAP stuff for pgTAP
  cpanm: name=TAP::Parser::SourceHandler::pgTAP

- name: Download pgTAP from github
  git: repo=https://github.com/theory/pgtap dest=~/pgtap

- name: run make on pgtap
  command: bash -lc 'cd ~/pgtap && make'
  register: _post_make_pgtap
  changed_when: _post_make_pgtap.stdout.find("Nothing to be done for `all\'") == -1

- name: install pgtap
  command: bash -lc 'cd ~/pgtap && make installcheck PGUSER=postgres && make install'
  when: _post_make_pgtap.stdout.find("Nothing to be done for `all\'") == -1

- name: load pgTAP into conceptql_test database
  command: bash -lc 'echo "CREATE EXTENSION pgtap;" | psql -d conceptql_test'
  sudo_user: postgres
  register: _post_load_pgtap_ext
  changed_when: _post_load_pgtap_ext.stdout.find('CREATE EXTENSION') != -1
