---
- name: Copy test_conceptql
  git: repo=https://github.com/outcomesinsights/test_conceptql.git dest={{ test_conceptql_dir}} update=no

- name: Copy over .env
  copy: src=.env dest={{ test_conceptql_dir }}/.env

- name: Remove database.yml
  file: dest={{ test_conceptql_dir }}/config/database.yml state=absent
  ignore_errors: True
  changed_when: False

- name: Update Gemfile to use local ConceptQL
  replace: dest={{ test_conceptql_dir }}/Gemfile regexp="^(gem 'conceptql')$" replace="\1, :path => '../conceptql'"

- name: Install test_conceptql gems via bundler
  command: bash -lc "cd {{ test_conceptql_dir }} && bundle"
  register: _tcql_install_gems_via_bundler
  changed_when: _tcql_install_gems_via_bundler.stdout.find('Installing') != -1

- name: Update Gemfile using sequelizer
  command: bash -lc "cd {{ test_conceptql_dir }} && bundle exec sequelizer update_gemfile"
  register: _tcql_update_gemfile
  changed_when: _tcql_update_gemfile.stdout.find('no modification') == -1

- name: Load validation data
  command: bash -lc "cd {{ test_conceptql_dir }} && bundle exec rake validate:load_data"
  register: _tcql_load_validation_data
  changed_when: _tcql_load_validation_data.stdout.find('rebuilding') != -1

- name: Load benchmark data
  command: bash -lc "cd {{ test_conceptql_dir }} && bundle exec rake benchmark:load_data"
  register: _tcql_load_benchmark_data
  changed_when: _tcql_load_benchmark_data.stdout.find('rebuilding') != -1

- name: Index all the things
  command: bash -lc "cd {{ test_conceptql_dir }} && bundle exec ruby db.rb index_all_the_things _bm1"
  register: _tcql_index_all_the_things
  changed_when: _tcql_index_all_the_things.stdout.find('indexed already') == -1

- name: Install loadmop gem
  command: bash -lc 'gem install -v ">= 0.0.3" loadmop'

- name: Check for vocabulary 4.3 data
  command: bash -lc 'echo "select count(*) from vocabulary.vocabulary;" | psql -d conceptql_test | grep 46'
  register: _tcql_vocab_43_check
  ignore_errors: True
  changed_when: False

- name: Check for vocabulary 4.4 data
  command: bash -lc 'echo "select count(*) from vocabulary.vocabulary;" | psql -d conceptql_test | grep 50'
  register: _tcql_vocab_44_check
  ignore_errors: True
  changed_when: False

- name: Setup vocabulary database
  command: bash -lc 'cd {{ test_conceptql_dir }} && loadmop create_vocab_database -s vocabulary {{ tcql.dest_dir }}/omop_vocab'
  when: _tcql_vocab_43_check.rc != 0 and  _tcql_vocab_44_check.rc != 0
