---
- hosts: all
  sudo: yes
  vars:
    postgresql_ext_install_dev_headers: true
    postgresql_ext_install_contrib: true
    postgresql_databases:
      - name: conceptql_test
    postgresql_users:
      - name: vagrant
        pass: v
    postgresql_user_privileges:
      - name: vagrant
        db: conceptql_test
    postgresql_pg_hba_passwd_hosts:
      - 192.168.0.1/16
      - 10.0.0.0/16
      - 172.28.0.0/16
    postgresql_listen_addresses:
      - '*'
    postgresql_work_mem: 1000MB
  roles:
    - add_packages
    - Ansibles.postgresql

