---
- hosts: all
  vars:
    rvm:
      root: ~/.rvm
      init_script: ~/.rvm/scripts/rvm
      url: https://get.rvm.io
      temp_installer_path: /tmp/rvm-installer.sh
      ruby_version: ruby-2.1.2
    tcql:
      dest_dir: '/vagrant'
      user: 'vagrant'
      group: 'vagrant'

  roles:
    - altermn.rvm
    - conceptql
    - dbtap
    - ruby_oci8
    - tinytds
    - { role: prep_data, file_name: sample_validation_data, file_md5: 5792c79c136d90b1f4ad354c65356822 }
    - { role: prep_data, file_name: sample_data, file_md5: 5f98fd74fad3e837ae6f18f57a3f3346 }
    - test_conceptql
