---
- name: Add packages
  apt: name={{ item }} state=latest
  with_items:
    - build-essential
    - cpanminus
    - curl
    - freetds-dev
    - freetds-bin
    - git
    - graphviz
    - libaio1
    - pgxnclient
    - python-psycopg2
    - postgresql-server-dev-9.3
    - tdsodbc
    - unzip

- name: Remove packages
  apt: name={{ item }} state=absent
  with_items:
    - puppet
    - puppet-common
